name: tournament-generator

services:

  generator-dev-api:
    container_name: generator-dev-api
    restart: always
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - DATABASE_URI=mysql+mysqlconnector://root:root@generator-dev-db:3306/generator-dev
      - CHOKIDAR_USEPOLLING=true
      - FLASK_DEBUG=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_APP=app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      generator-dev-db:
        condition: service_healthy

  generator-dev-db:
    image: mysql:8.4.4
    container_name: generator-dev-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: generator-dev
    healthcheck:
      test: mysqladmin ping -h localhost -uroot --password=$$MYSQL_ROOT_PASSWORD
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 55
    ports:
      - 3306:3306
    volumes:
      - generator-dev-db:/var/lib/mysql

volumes:
  generator-dev-db: